name: Pylint

# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Setup Pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint pylint-exit
          pip install -r requirements.txt
      - name: Run Pylint
        run: |
          pylint $(git ls-files '*.py') || pylint-exit $?
